parameters:
  appinsights_instrumentationkey: ''
  db_password: ''

steps:
- download: none    
- template: download-kubeconfig-file.yml

- script: kubectl --kubeconfig $AGENT_TEMPDIRECTORY/config create secret docker-registry $ACR_AUTHENTICATION_SECRET_NAME --namespace=$SYSTEM_STAGENAME --docker-server=$ACR_NAME.azurecr.io --docker-username=$ACR_NAME --docker-password=$ACRPASSWORD_ENV --dry-run -o yaml |  kubectl --kubeconfig $AGENT_TEMPDIRECTORY/config apply -f -
  env:
    ACRPASSWORD_ENV: $(acr_password)
  displayName: 'add or update ACR credentials for namespace'

- script: kubectl --kubeconfig $AGENT_TEMPDIRECTORY/config create configmap message.queue --from-literal=MESSAGE_QUEUE_URL=nats://message-queue-service:4222 --namespace=$SYSTEM_STAGENAME --dry-run -o yaml |  kubectl --kubeconfig $AGENT_TEMPDIRECTORY/config apply -f -
  displayName: 'add or update MESSAGE_QUEUE_URL configmap for namespace'

- script: kubectl --kubeconfig $AGENT_TEMPDIRECTORY/config create configmap appinsights.env --from-literal=APPINSIGHTS_INSTRUMENTATIONKEY=$APPINSIGHTS_INSTRUMENTATIONKEY --namespace=$SYSTEM_STAGENAME --dry-run -o yaml |  kubectl --kubeconfig $AGENT_TEMPDIRECTORY/config apply -f -
  displayName: 'add or update APPINSIGHTS_INSTRUMENTATIONKEY configmap configmap for namespace'

- script: kubectl --kubeconfig $AGENT_TEMPDIRECTORY/config create secret generic db.connection --from-literal=DB_CONNECTION_STRING="Server=tcp:$DB_SERVER_NAME.database.windows.net,1433;Initial Catalog=$SYSTEM_STAGENAME;Persist Security Info=False;User ID=sales_user_$SYSTEM_STAGENAME;Password=$DBPASSWORD_ENV;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;" --namespace=$SYSTEM_STAGENAME --dry-run -o yaml |  kubectl --kubeconfig $AGENT_TEMPDIRECTORY/config apply -f -
  env:
    DBPASSWORD_ENV: ${{parameters.db_password}}
  displayName: 'add or update DB_CONNECTION_STRING for namespace'

- script: kubectl --kubeconfig $AGENT_TEMPDIRECTORY/config create configmap aspnetcore.env --from-literal=ASPNETCORE_ENVIRONMENT=$SYSTEM_STAGENAME --namespace=$SYSTEM_STAGENAME --dry-run -o yaml |  kubectl --kubeconfig $AGENT_TEMPDIRECTORY/config apply -f -
  displayName: 'add or update ASPNETCORE_ENVIRONMENT for namespace'
