parameters:
  job_suffix: ''

jobs:
  - deployment: deploy_to_stage_${{ parameters.job_suffix }}
    displayName: 'deploy_to_stage_${{ parameters.job_suffix }}'
    environment: $(environment_name)  
    strategy:
      runOnce:
        deploy:
          steps:
            - template: output-variable-values.yml
          
            - template: download-kubeconfig-file.yml

            - script: kubectl --kubeconfig $AGENT_TEMPDIRECTORY/config apply -f $PIPELINE_WORKSPACE/k8s/message-queue-service.yaml --namespace=$SYSTEM_STAGENAME
              displayName: 'apply service for stage'

            - script: kubectl --kubeconfig $AGENT_TEMPDIRECTORY/config apply -f $PIPELINE_WORKSPACE/k8s/message-queue-deployment.yaml --namespace=$SYSTEM_STAGENAME
              displayName: 'apply deployment for stage'