name: '0.1.$(Rev:r)'

trigger: none

variables:
- group: megastore

pool:
  name: local
  demands:
  - agent.name -equals ubuntu-18.04  

stages:
- stage: init
  displayName: init
  jobs:
  - job: init
    workspace:
      clean: all
    steps:
    - template: templates/output-environment-variables.yml             
    - template: templates/publish-and-download-k8s-artefact.yml  

- stage: qa
  displayName: 'qa'
  dependsOn: init
  condition: succeeded('init')  
  jobs:
  - deployment: deploy_to_qa_stage
    displayName: deploy_to_qa_stage
    environment: $(environment_name)  
    strategy:
      runOnce:
        deploy:
          steps:
          - template: templates/output-environment-variables.yml
          - template: templates/megastore-message-queue-stage.yml

- stage: prd
  displayName: 'prd'
  dependsOn: qa
  condition: succeeded('qa')  
  jobs:
  - deployment: deploy_to_prd_stage
    displayName: deploy_to_prd_stage
    environment: $(environment_name)  
    strategy:
      runOnce:
        deploy:
          steps:
          - template: templates/output-environment-variables.yml
          - template: templates/megastore-message-queue-stage.yml