name: '0.1.$(Rev:r)'

trigger: none

variables:
- group: megastore

pool:
  name: local
  demands:
  - agent.name -equals ubuntu-18.04

stages:
- stage: build
  displayName: build
  jobs:
  - template: templates/publish-and-download-k8s-artefact.yml          

- stage: qa
  displayName: qa
  jobs:
  - template: templates/megastore-init-stage.yml
    parameters:
      job_name: ${{ 'configure_stage_for_qa' }}    
      appinsights_instrumentationkey: $(appinsights_instrumentationkey_qa)

- stage: prd
  displayName: prd
  jobs:
  - template: templates/megastore-init-stage.yml
    parameters:
      job_name: ${{ 'configure_stage_for_prd' }}    
      appinsights_instrumentationkey: $(appinsights_instrumentationkey_prd)