name: '0.1.$(Rev:r)'

trigger: none

variables:
- group: megastore

pool:
  name: local
  demands:
  - agent.name -equals $(local_linux_agent_name)  

stages:
- stage: init
  displayName: init
  variables:
  - name: service_name
    value: 'megastore.web'
  - name: image_name
    value: 'megastoreweb'
  jobs:
  - job: init
    workspace:
      clean: all
    steps:
    - template: templates/output-environment-variables.yml             
    - template: templates/publish-and-download-k8s-artefact.yml 
    - template: templates/megastore-build-push-image.yml
      parameters:    
        ServiceName: $(service_name)
        ImageName: $(image_name)

- stage: qa
  displayName: 'qa'
  dependsOn: init
  condition: succeeded('init')  
  jobs:
  - deployment: deploy_to_qa_stage
    displayName: deploy_to_qa_stage
    environment: $(environment_name)  
    strategy:
      runOnce:
        deploy:
          steps:
          - template: templates/output-environment-variables.yml
          - template: templates/megastore-web-stage.yml

- stage: prd
  displayName: 'prd'
  dependsOn: qa
  condition: succeeded('qa')  
  jobs:
  - deployment: deploy_to_prd_stage
    displayName: deploy_to_prd_stage
    environment: $(environment_name)  
    strategy:
      runOnce:
        deploy:
          steps:
          - template: templates/output-environment-variables.yml
          - template: templates/megastore-web-stage.yml