name: '0.1.$(Rev:r)'

trigger: none

variables:
- group: megastore

pool:
  name: local
  demands:
  - agent.name -equals ubuntu-18.04  

stages:
- stage: build
  displayName: build
  jobs:
  - template: templates/publish-and-download-k8s-artefact.yml

- stage: qa
  displayName: 'qa'
  - variables:
    - name: job_name
      value: 'deploy_to_stage_'$(System.StageName)'

  jobs:
  - template: templates/megastore-message-queue-stage.yml
    parameters:
      job_suffix: $(System.StageName)  

- stage: prd
  displayName: 'prd'
  dependsOn: qa
  condition: succeeded('qa')  
  jobs:
  - template: templates/megastore-message-queue-stage.yml