name: '0.1.$(Rev:r)'

trigger: none

variables:
- group: megastore

pool:
  name: local
  demands:
  - agent.name -equals ubuntu-18.04  

stages:
- stage: init
  displayName: init
  jobs:
  - template: templates/output-environment-variables.yml   
  - template: templates/clean-workspace-and-full-git-checkout.yml    
  - template: templates/publish-and-download-k8s-artefact.yml

- stage: qa
  displayName: 'qa'
  dependsOn: init
  condition: succeeded('init')  
  jobs:
  - template: templates/output-environment-variables.yml    
  - template: templates/megastore-message-queue-stage.yml
    parameters:
      job_name: ${{ 'deploy_to_qa_stage' }}  

- stage: prd
  displayName: 'prd'
  dependsOn: qa
  condition: succeeded('qa')  
  jobs:
  - template: templates/output-environment-variables.yml    
  - template: templates/megastore-message-queue-stage.yml
    parameters:
      job_name: ${{ 'deploy_to_prd_stage' }}     