version: '3.4'

services:

  message-queue:
    image: nats:linux
    networks:
      - ms-net

  megastore.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=dev
      - MESSAGE_QUEUE_URL=nats://message-queue:4222
      - APPINSIGHTS_INSTRUMENTATIONKEY=27f0cc11-f249-4d21-a7f5-1622cfdcc6be
    ports:
      - 80
    depends_on:
      - message-queue
    networks:
      - ms-net

  megastore.savesalehandler:
    environment:
      - MESSAGE_QUEUE_URL=nats://message-queue:4222
      - APPINSIGHTS_INSTRUMENTATIONKEY=27f0cc11-f249-4d21-a7f5-1622cfdcc6be
    env_file:
      - db-credentials.env
    depends_on:
      - message-queue
    networks:
      - ms-net

networks:
  ms-net: