version: '3.4'

services:

  message-queue:
    image: nats:linux
    networks:
      - ms-net

  megastore.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=dev
      - MESSAGE_QUEUE_URL=nats://message-queue:4222
      - APPINSIGHTS_INSTRUMENTATIONKEY=164030ad-ff9f-4402-9cce-dfb7f9d0a051
    ports:
      - 80
    depends_on:
      - message-queue
    networks:
      - ms-net

  megastore.savesalehandler:
    environment:
      - MESSAGE_QUEUE_URL=nats://message-queue:4222
      - APPINSIGHTS_INSTRUMENTATIONKEY=164030ad-ff9f-4402-9cce-dfb7f9d0a051
    env_file:
      - db-credentials.env
    depends_on:
      - message-queue
    networks:
      - ms-net

networks:
  ms-net: